sudo: false
language: python
cache: pip

matrix:
  include:
    - python: 2.7
      env:
        - TOXENV=django111-py27

install:
  - pip install tox
  - pip install coveralls

script:
  - tox

after_success:
  - coveralls
