language: python
cache: pip

matrix:
  include:
    - python: 2.7
      env:
        - TOXENV=django111
    - python: 3.5
      env:
        - TOXENV=django20

install:
  - pip install tox
  - pip install coveralls

script:
  - tox

after_success:
  - coveralls
