sudo: false
language: python
cache: pip

matrix:
  include:
    - python: 2.7
      env:
        - TOXENV=django111-py27
    - python: 3.5
      env:
       - TOXENV=django111-py35
    - python: 3.6
      env:
       - TOXENV=django111-py36

install:
  - pip install tox
  - pip install coveralls

script:
  - tox

after_success:
  - coveralls
