# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jmbo', '0007_auto_20170314_1546'),
        ('link', '0002_auto_20160902_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jmbo.ModelBase')),
                ('link', models.ForeignKey(help_text='Link to which this banner should redirect.', on_delete=django.db.models.deletion.CASCADE, to='link.Link')),
            ],
            bases=('jmbo.modelbase',),
        ),
    ]
