# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 19:27
from __future__ import unicode_literals

from django.db import migrations, models

from banner.styles import BANNER_STYLE_CLASSES


# Silence new migrations for styles choices alterations
def styles():
    return [
        (klass.__name__, klass.__name__)
        for klass in BANNER_STYLE_CLASSES
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='style',
            field=models.CharField(choices=styles(), default=b'BaseStyle', max_length=128),
        ),
    ]
