# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_auto_20171027_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='banner',
            field=models.ManyToManyField(blank=True, null=True, related_name='buttons', to='banner.Banner'),
        ),
    ]
