# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_button_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banner.Banner')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AlterField(
            model_name='button',
            name='text',
            field=models.CharField(help_text='The text to be displayed as the button label', max_length=60),
        ),
        migrations.AddField(
            model_name='buttonorder',
            name='button',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banner.Button'),
        ),
    ]
