# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0006_auto_20171029_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='style',
            field=models.CharField(default=b'Standard', max_length=128),
        ),
    ]
