# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0007_auto_20171029_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.ForeignKey(blank=True, help_text='Link to which this banner should redirect.', null=True, on_delete=django.db.models.deletion.CASCADE, to='link.Link'),
        ),
    ]
