# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0008_auto_20171030_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='background_image',
        ),
        migrations.AlterField(
            model_name='banner',
            name='style',
            field=models.CharField(choices=[(b'BaseStyle', b'BaseStyle')], max_length=128),
        ),
        migrations.AlterField(
            model_name='button',
            name='banner',
            field=models.ManyToManyField(blank=True, null=True, related_name='buttons', through='banner.ButtonOrder', to='banner.Banner'),
        ),
    ]
