# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0009_auto_20171108_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='body',
            field=simplemde.fields.SimpleMDEField(blank=True, help_text="The banner's main text content.", null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='headline',
            field=simplemde.fields.SimpleMDEField(blank=True, help_text="The banner's headline.", null=True),
        ),
    ]
